//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIBRARYMANAGEMENTSYSTEM.admin {
    
    
    public partial class PaymentInvioce {
        /// <summary>
        /// lbl_barcode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl lbl_barcode;

        /// <summary>
        /// ImageGeneratedBarcode control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image ImageGeneratedBarcode;
        /// <summary>
        /// lbl_invoicenumber control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_invoicenumber;

        /// <summary>
        /// lbl_OrderIDDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_OrderIDDate;

        /// <summary>
        /// lbl_Inviocername control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_Inviocername;

        /// <summary>
        /// lbl_invoiceremail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_invoiceremail;

        /// <summary>
        /// lbl_invoicermobile control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_invoicermobile;

        /// <summary>
        /// lbl_membershiptype control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_membershiptype;

        /// <summary>
        /// lbl_amount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_amount;

        /// <summary>
        /// lbl_totalamount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_totalamount;

        /// <summary>
        /// lbl_finaltotal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_finaltotal;

        protected global::System.Web.UI.WebControls.Label lbl_typename;
        protected global::System.Web.UI.WebControls.Label lbl_invoiceto;

        protected global::System.Web.UI.WebControls.Panel pnl_eachprice;
        protected global::System.Web.UI.WebControls.Panel pnl_eachpricevalue;
        protected global::System.Web.UI.WebControls.Label lbl_eachpricevalue;

        protected global::System.Web.UI.WebControls.Panel pnl_judicialstamphead;
        protected global::System.Web.UI.WebControls.Panel pnl_judicialstampvalue;
        protected global::System.Web.UI.WebControls.Label lbl_addressvalue;
        protected global::System.Web.UI.WebControls.Label lbl_Nameofstampvalue;
    }
}
